source 'https://rubygems.org'
ruby "1.9.3"

gem 'rails', '3.2.13'
gem 'unicorn'
gem 'secure_headers'
gem 'jquery-rails'
gem 'haml-rails'
gem 'pg'
gem 'rack-canonical-host'
# gem 'paperclip'
# gem 'aws-sdk'
# gem 'paranoia'
# gem 'omniauth'
# gem 'omniauth-facebook'
# gem 'kaminari'
# gem 'acts_as_hashed'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem "letter_opener"
  gem 'foreman'
  gem 'integration', git: 'git://github.com/mergulhao/integration.git'
  gem 'heroku-deploy'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'webmock'
  gem 'shoulda-matchers'
  gem 'timecop'
  gem 'simplecov', require: false
  gem 'capybara'
  gem 'poltergeist'
  gem 'valid_attribute'
  gem 'email_spec'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'dotenv-rails'
  gem 'awesome_print'
  # gem 'guard-rspec'
end
